version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: danangtrip_app
    volumes:
      - ./:/var/www
    working_dir: /var/www
    dns:
      - 8.8.8.8
    networks:
      - danangtrip

  nginx:
    image: nginx:latest
    container_name: danangtrip_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - danangtrip

  # db:
  #   image: mysql:8
  #   container_name: danangtrip_db
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: danang_trip
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - danangtrip

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   container_name: danangtrip_phpmyadmin
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: db
  #     PMA_USER: root
  #     PMA_PASSWORD: root
  #   depends_on:
  #     - db
  #   networks:
  #     - danangtrip

volumes:
  db_data: {}

networks:
  danangtrip:
    driver: bridge
